"""set nullable columns

Revision ID: 5b23eff882c0
Revises: 6a4b94cff797
Create Date: 2022-08-04 23:39:26.738768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b23eff882c0'
down_revision = '6a4b94cff797'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blog_article', 'status', nullable=True)
    op.alter_column('blog_article', 'publication_date', nullable=True)           
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
